num=int(input("enter the number :"))
temp=num
message=str()

div=temp//10000000
print(div)
if div != 0:
	if(div<20):
		if(div==1):
			message+="one"
		if(div==2):
			message+="two"
		if(div==3):
			message+="three"
		if(div==4):
			message+="four"
		if(div==5):
			message+="five"
		if(div==6):
			message+="six"
		if(div==7):
			message+="seven"
		if(div==8):
			message+="eight"
		if(div==9):
			message+="nine"
		if(div==10):
			message+="ten"
		if(div==11):
			message+="eleven"
		if(div==12):
			message+="twelve"
		if(div==13):
			message+="thirteen"
		if(div==14):
			message+="fouteen"
		if(div==15):
			message+="fifteen"
		if(div==16):
			message+="sixteen"
		if(div==17):
			message+="seventeen"
		if(div==18):
			message+="eighteen"
		if(div==19):
			message+="nineteen"
	else:
		q1=div//10
		
		if(q1==2):
			message+="twenty"
		if(q1==3):
			message+="thirty"
		if(q1==4):
			message+="forty"
		if(q1==5):
			message+="fifty"
		if(q1==6):
			message+="sixty"
		if(q1==7):
			message+="seventy"
		if(q1==8):
			message+="eighty"
		if(q1==9):
			message+="ninty"
		q2=div%10
		if (q2!=0):
			if(q2==1):
				message+="one"
			if(q2==2):
				message+="two"
			if(q2==3):
				message+="three"
			if(q2==4):
				message+="four"
			if(q2==5):
				message+="five"
			if(q2==6):
				message+="six"
			if(q2==7):
				message+="seven"
			if(q2==8):
				message+="eight"
			if(q2==9):
				message+="nine"
	message+=" crore "
temp=temp%10000000	
div=temp//100000
if div != 0:
	if(div<20):
		if(div==1):
			message+="one"
		if(div==2):
			message+="two"
		if(div==3):
			message+="three"
		if(div==4):
			message+="four"
		if(div==5):
			message+="five"
		if(div==6):
			message+="six"
		if(div==7):
			message+="seven"
		if(div==8):
			message+="eight"
		if(div==9):
			message+="nine"
		if(div==10):
			message+="ten"
		if(div==11):
			message+="eleven"
		if(div==12):
			message+="twelve"
		if(div==13):
			message+="thirteen"
		if(div==14):
			message+="fouteen"
		if(div==15):
			message+="fifteen"
		if(div==16):
			message+="sixteen"
		if(div==17):
			message+="seventeen"
		if(div==18):
			message+="eighteen"
		if(div==19):
			message+="nineteen"
	else:
		q1=div//10
		
		if(q1==2):
			message+="twenty"
		if(q1==3):
			message+="thirty"
		if(q1==4):
			message+="forty"
		if(q1==5):
			message+="fifty"
		if(q1==6):
			message+="sixty"
		if(q1==7):
			message+="seventy"
		if(q1==8):
			message+="eighty"
		if(q1==9):
			message+="ninty"
		q2=div%10
		if (q2!=0):
			if(q2==1):
				message+="one"
			if(q2==2):
				message+="two"
			if(q2==3):
				message+="three"
			if(q2==4):
				message+="four"
			if(q2==5):
				message+="five"
			if(q2==6):
				message+="six"
			if(q2==7):
				message+="seven"
			if(q2==8):
				message+="eight"
			if(q2==9):
				message+="nine"
	message+="  lakh  "
temp=temp%100000
div=temp//1000

if div != 0:
	if(div<20):
		if(div==1):
			message+="one"
		if(div==2):
			message+="two"
		if(div==3):
			message+="three"
		if(div==4):
			message+="four"
		if(div==5):
			message+="five"
		if(div==6):
			message+="six"
		if(div==7):
			message+="seven"
		if(div==8):
			message+="eight"
		if(div==9):
			message+="nine"
		if(div==10):
			message+="ten"
		if(div==11):
			message+="eleven"
		if(div==12):
			message+="twelve"
		if(div==13):
			message+="thirteen"
		if(div==14):
			message+="fouteen"
		if(div==15):
			message+="fifteen"
		if(div==16):
			message+="sixteen"
		if(div==17):
			message+="seventeen"
		if(div==18):
			message+="eighteen"
		if(div==19):
			message+="nineteen"
	else:
		q1=div//10
		if(q1==2):
			message+="twenty"
		if(q1==3):
			message+="thirty"
		if(q1==4):
			message+="forty"
		if(q1==5):
			message+="fifty"
		if(q1==6):
			message+="sixty"
		if(q1==7):
			message+="seventy"
		if(q1==8):
			message+="eighty"
		if(q1==9):
			message+="ninty"
		q2=div%10
		if (q2!=0):
			if(q2==1):
				message+="one"
			if(q2==2):
				message+="two"
			if(q2==3):
				message+="three"
			if(q2==4):
				message+="four"
			if(q2==5):
				message+="five"
			if(q2==6):
				message+="six"
			if(q2==7):
				message+="seven"
			if(q2==8):
				message+="eight"
			if(q2==9):
				message+="nine"
	message+="  thousand  "
	
temp=temp%1000
div=temp//100

if div != 0:
	if(div<20):
		if(div==1):
			message+="one"
		if(div==2):
			message+="two"
		if(div==3):
			message+="three"
		if(div==4):
			message+="four"
		if(div==5):
			message+="five"
		if(div==6):
			message+="six"
		if(div==7):
			message+="seven"
		if(div==8):
			message+="eight"
		if(div==9):
			message+="nine"
		if(div==10):
			message+="ten"
		if(div==11):
			message+="eleven"
		if(div==12):
			message+="twelve"
		if(div==13):
			message+="thirteen"
		if(div==14):
			message+="fouteen"
		if(div==15):
			message+="fifteen"
		if(div==16):
			message+="sixteen"
		if(div==17):
			message+="seventeen"
		if(div==18):
			message+="eighteen"
		if(div==19):
			message+="nineteen"
	else:
		q1=div//10
		
		if(q1==2):
			message+="twenty"
		if(q1==3):
			message+="thirty"
		if(q1==4):
			message+="forty"
		if(q1==5):
			message+="fifty"
		if(q1==6):
			message+="sixty"
		if(q1==7):
			message+="seventy"
		if(q1==8):
			message+="eighty"
		if(q1==9):
			message+="ninty"
		q2=div%10
		if (q2!=0):
			if(q2==1):
				message+="one"
			if(q2==2):
				message+="two"
			if(q2==3):
				message+="three"
			if(q2==4):
				message+="four"
			if(q2==5):
				message+="five"
			if(q2==6):
				message+="six"
			if(q2==7):
				message+="seven"
			if(q2==8):
				message+="eight"
			if(q2==9):
				message+="nine"
	message+="  hundred  "

div=div%100
if div != 0:
	if(div<20):
		if(div==1):
			message+="one"
		if(div==2):
			message+="two"
		if(div==3):
			message+="three"
		if(div==4):
			message+="four"
		if(div==5):
			message+="five"
		if(div==6):
			message+="six"
		if(div==7):
			message+="seven"
		if(div==8):
			message+="eight"
		if(div==9):
			message+="nine"
		if(div==10):
			message+="ten"
		if(div==11):
			message+="eleven"
		if(div==12):
			message+="twelve"
		if(div==13):
			message+="thirteen"
		if(div==14):
			message+="fouteen"
		if(div==15):
			message+="fifteen"
		if(div==16):
			message+="sixteen"
		if(div==17):
			message+="seventeen"
		if(div==18):
			message+="eighteen"
		if(div==19):
			message+="nineteen"
	else:
		q1=div//10		
		if(q1==2):
			message+="twenty"
		if(q1==3):
			message+="thirty"
		if(q1==4):
			message+="forty"
		if(q1==5):
			message+="fifty"
		if(q1==6):
			message+="sixty"
		if(q1==7):
			message+="seventy"
		if(q1==8):
			message+="eighty"
		if(q1==9):
			message+="ninty"
		q2=div%10
		if (q2!=0):
			if(q2==1):
				message+="one"
			if(q2==2):
				message+="two"
			if(q2==3):
				message+="three"
			if(q2==4):
				message+="four"
			if(q2==5):
				message+="five"
			if(q2==6):
				message+="six"
			if(q2==7):
				message+="seven"
			if(q2==8):
				message+="eight"
			if(q2==9):
				message+="nine"
print(message)


